language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - 2.7.0
  - ruby-head
before_install:
  - gem install bundler:2.1.1
script:
  - bundle exec rspec
  - bundle exec rubocop
matrix:
 allow_failures:
   - rvm: ruby-head
